<?php

namespace Tests\Unit;

use Dev\Domain\Service\DataProviderYService;
use Tests\TestCase;

class DataProviderYTest extends TestCase
{
    private $dataProviderYService;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->dataProviderYService = app(DataProviderYService::class);
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function testExample()
    {
        $this->assertTrue(true);
    }

    public function testGetData()
    {
        $data = $this->dataProviderYService->getData();
        $this->assertIsArray($data);
        if ($data) {
            $this->assertNotEmpty($data);
            $this->assertArrayHasKey('balance', $data[0]);
            $this->assertArrayHasKey('currency', $data[0]);
            $this->assertArrayHasKey('email', $data[0]);
            $this->assertArrayHasKey('status', $data[0]);
            $this->assertArrayHasKey('registration_date', $data[0]);
            $this->assertArrayHasKey('identification', $data[0]);
        }
    }
}
